chore(sync-files): remove pre-commit-config.yaml from sync-files
tier4/CARET_analyze_cpp_impl pull request #45
Opened 2022-10-28 05:26 UTC by hsgwa

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>

This PR removes pre-commit-config.yaml from sync-files to fix sync-files and pre-commit-ci confliction.

- https://github.com/tier4/CARET_analyze_cpp_impl/pull/43
- https://github.com/tier4/CARET_analyze_cpp_impl/pull/40

After applying this PR, sync-files can be applied.

2022-10-31 04:38 UTC, keita1523 commented
LGTM

The following PRs are autoware.universe's PRs and opened now.
- [chore: sync file](https://github.com/autowarefoundation/autoware.universe/pull/2146)
- [ci(pre-commit): autoupdate](https://github.com/autowarefoundation/autoware.universe/pull/1656)

2022-10-31 11:11 UTC, keita1523 reviewed
I think that "comment out" maybe better.

2022-11-02 00:15 UTC, hsgwa commented
@keita1523 
I added a comment.
> I think that "comment out" maybe better.

2022-11-02 01:05 UTC, keita1523 approved these changes
LGTM

2022-11-14 05:18 UTC, takam5f2 approved these changes
LGTM

2022-11-14 05:20 UTC, takam5f2 requested changes
Could you fix errors found in Github Ation?

2022-11-14 06:19 UTC, hsgwa commented
@takam5f2 
I fixed in: 6ee7317
> Could you fix errors found in Github Ation?

2022-11-14 07:55 UTC, takam5f2 approved these changes
LGTM

2022-11-14 07:56 UTC, merged